main: GL_Related_hw4p2.cpp math3d.cpp math3d.h particle.h Simulation.cpp Simulation.h
	g++ GL_Related_hw4p2.cpp Simulation.cpp math3d.cpp -framework OpenGL -framework GLUT -o main

clean: 
	rm -f main